project_id = "ikurrflncrgwntpkmblg"

[functions.public-event-rsvp]
verify_jwt = false

[functions.admin-invite-user]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.public-ambassador-lookup]
verify_jwt = false
